CategoryBundle\Entity\Category:
    type:  entity
    table: category
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
        description:
            type: text
            nullable: true
            fixed: false
        parentCategory:
            type: integer
            nullable: true
        photoCategory:
              type: text
              nullable: true




    lifecycleCallbacks: {  }
