ClientsOrderStatusBundle\Entity\ClientsOrderStatus:
    type:  entity
    table: clients_order_status
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: false
        desctiption:
            type: text
            nullable: true

    lifecycleCallbacks: {  }
