ClientBundle\Entity\Client:
    type:  entity
    table: client
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: text
            nullable: true
            fixed: false


    lifecycleCallbacks: {  }
