ClientBundle\Entity\Client:
    type:  entity
    table: client
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: text
            nullable: true
            fixed: false
        phone:
            type: string
            nullable: true
            length: 255
            fixed: false

    oneToMany:
        adress:
            targetEntity: ClientAdressBundle\Entity\ClientAdress
            mappedBy: ClientAdress





    lifecycleCallbacks: {  }
