UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
            nullable: true
            fixed: false
        phone:
            type: string
            nullable: true
            length: 255
            fixed: false
        age:
            type: string
            nullable: true
            length: 10
            fixed: false
        passport:
            type: string
            nullable: true
            length: 255
            fixed: false
        photoUser:
            type: string
            nullable: true
            fixed: false
            length: 255
    lifecycleCallbacks: {  }
