OrderBundle\Entity\Order:
    type:  entity
    table: clients_order
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        dateCreated:
            type: datetime
            nullable: false
        dateFinish:
            type: datetime
            nullable: false
        description:
            type: text
            nullable: true
            fixed: false
        status:
            type: integer
            nullable: true
        products:
            type: text
            nullable: true
        price_total:
              type: integer
              nullable: true
        client:
              type: string
              nullable: true
        clientAdress:
            type: string
            nullable: true
        phone:
            type: string
            nullable: true
        price_deliver:
            type: integer
            nullable: true

    oneToOne:
        man_doit:
            targetEntity: UserBundle\Entity\User

    man_created:
            man_doit:
                targetEntity: UserBundle\Entity\User

    oneToOne:
        clientsOrderStatus:
            targetEntity: ClientsOrderStatusBundle\Entity\ClientsOrderStatus



    lifecycleCallbacks: {  }
