ProductPropertiesBundle\Entity\ProductProperties:
    type:  entity
    table: product_properties
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
        description:
            type: text
            nullable: true
            fixed: false


    lifecycleCallbacks: {  }
