ClientAdressBundle\Entity\ClientAdress:
    type:  entity
    table: client_adress
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
            nullable: true
            fixed: false
        adress:
            type: text
            nullable: false
            fixed: false
        phone:
            type: string
            nullable: true
            length: 255
    manyToOne:
          client:
              targetEntity: ClientBundle\Entity\Client


    lifecycleCallbacks: {  }
