order_index:
    path:     /
    defaults: { _controller: "OrderBundle:Order:index" }
    methods:  GET

order_show:
    path:     /{id}/show
    defaults: { _controller: "OrderBundle:Order:show" }
    methods:  GET

order_new:
    path:     /new
    defaults: { _controller: "OrderBundle:Order:new" }
    methods:  [GET, POST]

set_new_order:
    path: /set_new_order
    defaults: {_controller: "OrderBundle:Order:setNewOeder"}
    methods: [POST]




order_edit:
    path:     /{id}/edit
    defaults: { _controller: "OrderBundle:Order:edit" }
    methods:  [GET, POST]

order_delete:
    path:     /{id}/delete
    defaults: { _controller: "OrderBundle:Order:delete" }
    methods:  DELETE
