clientsorderstatus_index:
    path:     /
    defaults: { _controller: "ClientsOrderStatusBundle:ClientsOrderStatus:index" }
    methods:  GET

clientsorderstatus_show:
    path:     /{id}/show
    defaults: { _controller: "ClientsOrderStatusBundle:ClientsOrderStatus:show" }
    methods:  GET

clientsorderstatus_new:
    path:     /new
    defaults: { _controller: "ClientsOrderStatusBundle:ClientsOrderStatus:new" }
    methods:  [GET, POST]

clientsorderstatus_edit:
    path:     /{id}/edit
    defaults: { _controller: "ClientsOrderStatusBundle:ClientsOrderStatus:edit" }
    methods:  [GET, POST]

clientsorderstatus_delete:
    path:     /{id}/delete
    defaults: { _controller: "ClientsOrderStatusBundle:ClientsOrderStatus:delete" }
    methods:  DELETE
