ClientPhoneBundle\Entity\ClientPhone:
    type:  entity
    table: client_phone
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        phone:
            type: string
            length: 255
    manyToOne:
          client:
              targetEntity: ClientBundle\Entity\Client


    lifecycleCallbacks: {  }
